# Generated by Django 2.2.4 on 2019-12-15 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='地区编号')),
                ('Name', models.CharField(default='北京', max_length=5, verbose_name='地区名字')),
            ],
            options={
                'db_table': 'Area',
                'verbose_name': '地区',
                'verbose_name_plural': '地区列表',
            },
        ),
        migrations.CreateModel(
            name='ComdyClass',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False, verbose_name='商品类别编号')),
                ('CName', models.CharField(default='未设置', max_length=10, verbose_name='类别名称')),
                ('CStatement', models.CharField(max_length=100, null=True, verbose_name='类别说明')),
            ],
            options={
                'db_table': 'ComdyClass',
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别列表',
            },
        ),
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False, verbose_name='商品编号')),
                ('CName', models.CharField(default='', max_length=20, verbose_name='商品名称')),
                ('CCount', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('CState', models.CharField(default='售卖中', max_length=10, verbose_name='状态')),
                ('CPurchasesCount', models.PositiveIntegerField(default=0, verbose_name='已购买量')),
                ('CPrice', models.FloatField(default=0, verbose_name='价格')),
                ('CStatement', models.TextField(default='（空）', verbose_name='商品介绍')),
                ('CArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Area', verbose_name='发货地区')),
                ('CCid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ComdyClass', verbose_name='类别')),
            ],
            options={
                'db_table': 'ComdyInfo',
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别列表',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPhone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号')),
                ('UBirthday', models.DateField(blank=True, null=True, verbose_name='用户生日')),
                ('USex', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='用户性别')),
                ('UStatement', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='用户个人说明')),
                ('Unickname', models.CharField(blank=True, default='', max_length=10, verbose_name='用户昵称')),
                ('img', models.ImageField(default='HeadPortrait\\defult.png', upload_to='HeadPortrait', verbose_name='用户头像')),
                ('UserBase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Users',
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户列表',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('STime', models.DateTimeField(verbose_name='交易时间')),
                ('SCount', models.PositiveIntegerField(default=1, verbose_name='成交商品数量')),
                ('STotalAmount', models.FloatField(default=0, verbose_name='成交总额')),
                ('SState', models.CharField(default='成功', max_length=10, verbose_name='交易状态')),
                ('SRemark', models.TextField(default='', verbose_name='买家备注')),
                ('SComdyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CommodityInfo', verbose_name='商品编号')),
                ('SUsersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.UserMessage', verbose_name='用户编号')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='日志记录时间')),
                ('Statement', models.CharField(default='', max_length=100, verbose_name='日志内容')),
                ('ComdyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CommodityInfo', verbose_name='商品编号')),
                ('UsersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.UserMessage', verbose_name='用户编号')),
            ],
            options={
                'db_table': 'Log',
                'verbose_name': '日志记录',
                'verbose_name_plural': '日志记录列表',
            },
        ),
        migrations.CreateModel(
            name='BasketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarkTime', models.DateTimeField(auto_now_add=True, verbose_name='加入购物篮时间')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='添加的数量')),
                ('ComdyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CommodityInfo', verbose_name='商品编号')),
                ('UsersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.UserMessage', verbose_name='用户编号')),
            ],
            options={
                'db_table': 'BasketMessage',
                'verbose_name': '购物篮记录',
                'verbose_name_plural': '购物篮记录列表',
            },
        ),
    ]
