# Generated by Django 2.2.4 on 2019-12-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesrecord',
            options={'verbose_name': '销售记录', 'verbose_name_plural': '销售记录列表'},
        ),
        migrations.AlterField(
            model_name='comdyclass',
            name='CStatement',
            field=models.CharField(max_length=200, null=True, verbose_name='类别说明'),
        ),
        migrations.AlterModelTable(
            name='salesrecord',
            table='SalesRecord',
        ),
    ]
