# Generated by Django 2.2.4 on 2019-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191215_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodityinfo',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息列表'},
        ),
        migrations.AddField(
            model_name='commodityinfo',
            name='img',
            field=models.ImageField(default='CommodityImg\\defult.png', upload_to='CommodityImg', verbose_name='商品图片'),
        ),
    ]
