# Generated by Django 2.2.4 on 2019-12-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191215_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfo',
            name='CName',
            field=models.CharField(default='', max_length=50, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='commodityinfo',
            name='CState',
            field=models.CharField(default='售卖中', max_length=20, verbose_name='状态'),
        ),
    ]
