# Generated by Django 2.2.8 on 2019-12-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20191215_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmessage',
            name='UsersId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.UserMessage', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='SState',
            field=models.CharField(default='已付款', max_length=10, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='STime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='UPhone',
            field=models.CharField(blank=True, default='none', max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='USex',
            field=models.CharField(blank=True, default='X', max_length=2, null=True, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='UStatement',
            field=models.CharField(blank=True, default='none', max_length=150, null=True, verbose_name='用户个人说明'),
        ),
    ]
